---
title: Internment of Japanese Canadians
timezone: Canada/Calgary
collections:
  posts:
    title: Posts
    output: true
  steps:
    title: Steps
    output: false
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: steps
  values:
    title: 
    date: 2020-03-03 00:00:00 -0700
markdown: kramdown
highlighter: rouge
lsi: false
description: A breif comprehensive timeline of the history of Japanese Canadians
baseurl: "/japanese-canadian-timeline"
url: https:/yahyaasmara.github.io
color: "#f2f2f2"
